AllCops:
   TargetRubyVersion: 2.4

Style/EmptyLinesAroundClassBody:
   Description: Keeps track of empty lines around class bodies.
   Enabled: true
   EnforcedStyle: empty_lines
   SupportedStyles:
   - empty_lines
   - no_empty_lines

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: when_needed
  SupportedStyles:
  - when_needed
  - always

Debugger:
   Enabled: false
Style/FormatString:
   Description: Enforce the use of Kernel#sprintf, Kernel#format or String#%.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#sprintf
   Enabled: true
   EnforcedStyle: percent


Style/EmptyLinesAroundMethodBody:
   Description: Keeps track of empty lines around method bodies.
   Enabled: true

Style/TrailingWhitespace:
   Description: Avoid trailing whitespace.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-trailing-whitespace
   Enabled: false

Style/IndentationWidth:
   Description: Use 2 spaces for indentation.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#spaces-indentation
   Enabled: true
   Width: 2

Style/RegexpLiteral:
   Description: Use / or %r around regular expressions.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-r
   Enabled: true
   EnforcedStyle: slashes
   AllowInnerSlashes: true

Metrics/MethodLength:
   Description: Avoid methods longer than 30 lines of code.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
   Enabled: true
   CountComments: false
   Max: 30

Metrics/AbcSize:
   Description: A calculated magnitude based on number of assignments, branches, and conditions.
   Reference: http://c2.com/cgi/wiki?AbcMetric
   Enabled: true
   Max: 30

Style/SignalException:
   Description: Checks for proper usage of fail and raise.
   StyleGuide: https://github.com/bbatsov/ruby-style-guide#prefer-raise-over-fail
   Enabled: true
   EnforcedStyle: only_fail
   SupportedStyles:
   - only_raise
   - only_fail
   - semantic

Metrics/LineLength:
  Description: Limit lines to 80 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 200
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
  - http
  - https

